/*
	used to generate contours
	Mingdong
	2017/05/06
*/
#pragma once
#include "BasicStruct.h"

// 
class ContourGenerator
{
private:
	static ContourGenerator* s_pInstance;
public:
	static ContourGenerator* GetInstance() {
		if (!s_pInstance)
			s_pInstance = new ContourGenerator();
		return s_pInstance;
	}
	static void Release() {
		if (s_pInstance)
			delete s_pInstance;
	}
private:
	ContourGenerator();
	~ContourGenerator();
public:
	/*
		generate the contour
		data:			the scalar field
		listContour:	store the result
		fValue:			iso-value
		nWidth,nHeight:	width and height of the field
		x,y,w,h:		focused area
	*/
	void Generate(const double* data
		, QList<ContourLine>& listContour
		, double fValue
		, int nWidth
		, int nHeight
		);

private:
	// the segments generated by marching square
	QList<LineSeg> _listSeg;
	// the iso-value
	double _fValue;
	// the grid data
	const double* _data;

	int _nWidth;
	int _nHeight;
private:
	// generate the line strips by marching triangle
	void generateLineStrip_old();
	// generate the line strips by marching square
	void generateLineStrip();
	// combine the line strips
	void combineLineStrip(QList<ContourLine>& listContour);

};

